import 'dart:async';

import 'package:flutter/material.dart';
import 'package:indyen/login_signup.dart';
// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Splash extends StatefulWidget {
  const Splash({super.key});

  @override
  State<Splash> createState() => _SplashState();
}

class _SplashState extends State<Splash> {
  @override
  void initState() {
    super.initState();

    // Set up a timer to navigate to the main screen after 3 seconds
    Timer(Duration(seconds: 2), () {
      // Replace the current screen with the main screen
      Navigator.of(context).pushReplacement(
        MaterialPageRoute(builder: (context) => Login()),
      );
    });
  }
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
          height: MediaQuery.of(context).size.height,
          width: MediaQuery.of(context).size.width,
            decoration: BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
                colors: [
                  Color(0xFFFFFFFF), // Hex code for the starting color
                  Color(0xFFFFFCEF), // Hex code for the ending color
                ],
              ),
            ),
          child: Center(
              child: Image.asset("assets/images/logo.png")),
        ),
      );
  }
}